name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Yarn Install
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: install

      - name: Build
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: run ghPages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
